---
- hosts: all
  become: true
  vars:
    user_name: user

  tasks:
  - name: Installation for Ubuntu
    apt:
      name:
        - python3
        - python3-pip
        - openjdk-11-jdk
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Installation for CentOS
    dnf:
      name:
        - python3-pip
        - python3
        - java-11-openjdk-devel
      state: latest
    when: ansible_distribution == "CentOS"

  - name: default MOTD
    copy:
      content: "Ansible Managed node by ronquillo"
      dest: /etc/motd

  - name: Create user
    user:
      name: "{{ user_name }}"
      comment: "Ansible User"
      state: present
      createhome: yes
      shell: /bin/bash
